import { writable } from 'svelte/store';

// export const INDEX = writable(0);

// will help later
export const INDEX = writable(null);
export const HOVER = writable(null);
export const activeIndex = writable(null);

export const stationData = [
 {
   "name": "Dublab",
   "city": "Los Angeles",
   "country": "USA",
   "utc": "-8",
   "timezone": "America/Los_Angeles",
   "slug": "dublab",
   "url": "https://www.dublab.com/",
   "audio": "https://dublab.out.airtime.pro/dublab_a",
   "highlight": "D03D02",
   "fill": "F4F2EA",
   "sparkle": "D03D02",
   "mosaicBg": "D03D02"
 },
 {
   "name": "Lookout FM",
   "city": "Los Angeles",
   "country": "USA",
   "utc": "·",
   "timezone": "America/Los_Angeles",
   "slug": "lookout-fm",
   "url": "http://lookout.fm/",
   "audio": "https://radio.mensajito.mx/nopalradio",
   "highlight": "D9EAD3",
   "fill": "5A3474",
   "sparkle": "D9EAD3",
   "mosaicBg": "5A3474"
 },
 {
   "name": "Kchung",
   "city": "Los Angeles",
   "country": "USA",
   "utc": "·",
   "timezone": "America/Los_Angeles",
   "slug": "kchung",
   "url": "https://www.kchungradio.org/stream",
   "audio": "https://kchungradio.out.airtime.pro/kchungradio_a",
   "highlight": "690C1B",
   "fill": "9B5E2F",
   "sparkle": "F4F2EA",
   "mosaicBg": "690C1B"
 },
 {
   "name": "BFF.fm",
   "city": "San Francisco",
   "country": "USA",
   "utc": "·",
   "timezone": "America/Los_Angeles",
   "slug": "bff-fm",
   "url": "https://bff.fm/",
   "audio": "https://ais-sa2.cdnstream1.com/2053_128.mp3",
   "highlight": "1F3470",
   "fill": "D03D02",
   "sparkle": "F4F2EA",
   "mosaicBg": "1F3470"
 },
 {
   "name": "Internet Public Radio",
   "city": "Guadalajara",
   "country": "Mexico",
   "utc": "·",
   "timezone": "America/Mexico_City",
   "slug": "internet-public-radio",
   "url": "https://www.internetpublicradio.live/",
   "audio": "https://c11.radioboss.fm/stream/270",
   "highlight": "C55380",
   "fill": "F4F2EA",
   "sparkle": "C55380",
   "mosaicBg": "C55380"
 },
 {
   "name": "Radio Nopal",
   "city": "Mexico City",
   "country": "Mexico",
   "utc": "·",
   "timezone": "America/Mexico_City",
   "slug": "radio-nopal",
   "url": "https://radionopal.com/",
   "audio": "https://radio.mensajito.mx/nopalradio",
   "highlight": "5A3474",
   "fill": "24F58C",
   "sparkle": "1F3470",
   "mosaicBg": "1F3470"
 },
 {
   "name": "Radio Veintiocho",
   "city": "San Andrés Cholula",
   "country": "Mexico",
   "utc": "·",
   "timezone": "America/Mexico_City",
   "slug": "radio-veintiocho",
   "url": "https://www.radio28.net/",
   "audio": "https://www-radio28-net.filesusr.com/html/ffc736_d1a2c392d0663a4ef7734d41b498afb7.html",
   "highlight": "D03D02",
   "fill": "9B5E2F",
   "sparkle": "F4F2EA",
   "mosaicBg": "9B5E2F"
 },
 {
   "name": "8 Ball Radio",
   "city": "New York",
   "country": "USA",
   "utc": "-4",
   "timezone": "America/New_York",
   "slug": "8-ball-radio",
   "url": "https://8ballradio.nyc/",
   "audio": "https://eightball.out.airtime.pro/eightball_a",
   "highlight": "F4F2EA",
   "fill": "1F3470",
   "sparkle": "F4F2EA",
   "mosaicBg": "1F3470"
 },
 {
   "name": "Half Moon",
   "city": "New York",
   "country": "USA",
   "utc": "·",
   "timezone": "America/New_York",
   "slug": "half-moon",
   "url": "https://www.halfmoonbk.com/",
   "audio": "https://half-moon.radiocult.fm/stream",
   "highlight": "690C1B",
   "fill": "D9EAD3",
   "sparkle": "690C1B",
   "mosaicBg": "690C1B"
 },
 {
   "name": "N10.AS",
   "city": "Montreal",
   "country": "Canada",
   "utc": "·",
   "timezone": "America/Toronto",
   "slug": "n10-as",
   "url": "https://n10.as/",
   "audio": "https://n10as.radiocult.fm/stream",
   "highlight": "E196BF",
   "fill": "5A3474",
   "sparkle": "E196BF",
   "mosaicBg": "5A3474"
 },
 {
   "name": "Veneno",
   "city": "Sao Paulo",
   "country": "Brazil",
   "utc": "-3",
   "timezone": "America/Sao_Paulo",
   "slug": "veneno",
   "url": "https://veneno.live/",
   "audio": "https://veneno.out.airtime.pro/veneno_b",
   "highlight": "DBCDC2",
   "fill": "1F3470",
   "sparkle": "DBCDC2",
   "mosaicBg": "1F3470"
 },
 {
   "name": "Oroko Radio",
   "city": "Accra",
   "country": "Ghana",
   "utc": "0",
   "timezone": "Africa/Accra",
   "slug": "oroko-radio",
   "url": "https://oroko.live/",
   "audio": "https://oroko-radio.radiocult.fm/stream",
   "highlight": "5A3474",
   "fill": "F4F2EA",
   "sparkle": "5A3474",
   "mosaicBg": "5A3474"
 },
 {
   "name": "Seyðisfjörður Community Radio",
   "city": "Seyðisfjörður",
   "country": "Iceland",
   "utc": "·",
   "timezone": "Atlantic/Reykjavik",
   "slug": "seyoisfjorour-community-radio",
   "url": "https://seydisfjordurcommunityradio.net/",
   "audio": "https://seyisfjorur-community-radio.radiocult.fm/stream",
   "highlight": "690C1B",
   "fill": "E196BF",
   "sparkle": "690C1B",
   "mosaicBg": "690C1B"
 },
 {
   "name": "Dublin Digital Radio",
   "city": "Dublin",
   "country": "Ireland",
   "utc": "·",
   "timezone": "Europe/Dublin",
   "slug": "dublin-digital-radio",
   "url": "https://listen.dublindigitalradio.com/",
   "audio": "https://dublin-digital-radio.radiocult.fm/stream",
   "highlight": "CBCF8B",
   "fill": "1F3470",
   "sparkle": "CBCF8B",
   "mosaicBg": "1F3470"
 },
 {
   "name": "EHFM",
   "city": "Glasgow ",
   "country": "Scotland",
   "utc": "·",
   "timezone": "Europe/London",
   "slug": "eh-fm",
   "url": "https://www.ehfm.live/",
   "audio": "https://ehfm.out.airtime.pro/ehfm_a",
   "highlight": "9B5E2F",
   "fill": "D03D02",
   "sparkle": "3B071E",
   "mosaicBg": "3B071E"
 },
 {
   "name": "Sub City",
   "city": "Glasgow ",
   "country": "Scotland",
   "utc": "·",
   "timezone": "Europe/London",
   "slug": "sub-city",
   "url": "https://www.subcity.org/",
   "audio": "https://stream.subcity.org/listen",
   "highlight": "24F58C",
   "fill": "D8C92B",
   "sparkle": "3F5C3B",
   "mosaicBg": "3F5C3B"
 },
 {
   "name": "Noods FM",
   "city": "Bristol",
   "country": "England",
   "utc": "·",
   "timezone": "Europe/London",
   "slug": "noods-fm",
   "url": "https://noodsradio.com/",
   "audio": "https://noods-radio.radiocult.fm/stream",
   "highlight": "C8A048",
   "fill": "24F58C",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Reform Radio",
   "city": "Manchester",
   "country": "England",
   "utc": "·",
   "timezone": "Europe/London",
   "slug": "reform-radio",
   "url": "https://www.reformradio.co.uk/",
   "audio": "https://testform.out.airtime.pro/testform_a",
   "highlight": "1F3470",
   "fill": "F4F2EA",
   "sparkle": "1F3470",
   "mosaicBg": "1F3470"
 },
 {
   "name": "Do You",
   "city": "London",
   "country": "England",
   "utc": "·",
   "timezone": "Europe/London",
   "slug": "do-you",
   "url": "https://doyou.world/",
   "audio": "https://doyouworld.out.airtime.pro/doyouworld_a",
   "highlight": "FDBD2B",
   "fill": "3F5C3B",
   "sparkle": "FDBD2B",
   "mosaicBg": "3F5C3B"
 },
 {
   "name": "Bloop",
   "city": "London",
   "country": "England",
   "utc": "·",
   "timezone": "Europe/London",
   "slug": "bloop",
   "url": "https://blooplondon.com/",
   "audio": "http://radio.canstream.co.uk:8058/live.mp3",
   "highlight": "DBCDC2",
   "fill": "24F58C",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Netil Radio",
   "city": "London",
   "country": "England",
   "utc": "·",
   "timezone": "Europe/London",
   "slug": "netil-radio",
   "url": "https://netilradio.com/",
   "audio": "https://netilradio.out.airtime.pro/netilradio_a",
   "highlight": "7251A2",
   "fill": "D9EAD3",
   "sparkle": "3B071E",
   "mosaicBg": "3B071E"
 },
 {
   "name": "Foundation FM",
   "city": "London",
   "country": "England",
   "utc": "·",
   "timezone": "Europe/London",
   "slug": "foundation-fm",
   "url": "https://foundation.fm/",
   "audio": "https://streamer.radio.co/s0628bdd53/listen",
   "highlight": "E196BF",
   "fill": "690C1B",
   "sparkle": "FF008A",
   "mosaicBg": "690C1B"
 },
 {
   "name": "NTS 1",
   "city": "London",
   "country": "England",
   "utc": "·",
   "timezone": "Europe/London",
   "slug": "nts-1",
   "url": "https://www.nts.live/",
   "audio": "https://stream-relay-geo.ntslive.net/stream",
   "highlight": "F4F2EA",
   "fill": "CBCF8B",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "NTS 2",
   "city": "London",
   "country": "England",
   "utc": "·",
   "timezone": "Europe/London",
   "slug": "nts-2",
   "url": "https://www.nts.live/",
   "audio": "https://stream-relay-geo.ntslive.net/stream2",
   "highlight": "FF008A",
   "fill": "E196BF",
   "sparkle": "690C1B",
   "mosaicBg": "690C1B"
 },
 {
   "name": "Worldwide FM",
   "city": "London",
   "country": "England",
   "utc": "·",
   "timezone": "Europe/London",
   "slug": "worldwide-fm",
   "url": "https://worldwidefm.net/",
   "audio": "https://worldwidefm.out.airtime.pro/worldwidefm_b",
   "highlight": "690C1B",
   "fill": "9B5E2F",
   "sparkle": "F4F2EA",
   "mosaicBg": "9B5E2F"
 },
 {
   "name": "Radio Quantica",
   "city": "Lisbon",
   "country": "Portugal",
   "utc": "+1",
   "timezone": "Europe/Lisbon",
   "slug": "radio-quantica",
   "url": "https://www.radioquantica.com/",
   "audio": "https://libretime.radioquantica.com/main.mp3",
   "highlight": "24F58C",
   "fill": "C55380",
   "sparkle": "D9EAD3",
   "mosaicBg": "C55380"
 },
 {
   "name": "Kiosk Radio",
   "city": "Brussels",
   "country": "Belgium",
   "utc": "+1",
   "timezone": "Europe/Brussels",
   "slug": "kiosk-radio",
   "url": "https://kioskradio.com/",
   "audio": "https://kioskradiobxl.out.airtime.pro/kioskradiobxl_b",
   "highlight": "1F3470",
   "fill": "D9EAD3",
   "sparkle": "1F3470",
   "mosaicBg": "1F3470"
 },
 {
   "name": "Radio Panik",
   "city": "Brussels",
   "country": "Belgium",
   "utc": "·",
   "timezone": "Europe/Brussels",
   "slug": "radio-panik",
   "url": "https://www.radiopanik.org/",
   "audio": "https://streaming.domainepublic.net/radiopanik.ogg",
   "highlight": "331614",
   "fill": "DF888A",
   "sparkle": "331614",
   "mosaicBg": "FF008A"
 },
 {
   "name": "Lyl Radio",
   "city": "Lyon",
   "country": "France",
   "utc": "·",
   "timezone": "Europe/Paris",
   "slug": "lyl-radio",
   "url": "https://lyl.live/",
   "audio": "https://icecast.lyl.live/live",
   "highlight": "DF888A",
   "fill": "FDBD2B",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Radio Beguin",
   "city": "Lyon",
   "country": "France",
   "utc": "·",
   "timezone": "Europe/Paris",
   "slug": "radio-beguin",
   "url": "https://radiobeguin.com/",
   "audio": "https://listen.radioking.com/radio/284398/stream/330307",
   "highlight": "D9EAD3",
   "fill": "DF888A",
   "sparkle": "3B071E",
   "mosaicBg": "3B071E"
 },
 {
   "name": "Radio DY10",
   "city": "Nantes",
   "country": "France",
   "utc": "·",
   "timezone": "Europe/Paris",
   "slug": "radio-dy10",
   "url": "https://radiody10.com/",
   "audio": "https://flux.radiody10.com/airtime_128",
   "highlight": "8A96B0",
   "fill": "F4F2EA",
   "sparkle": "1F3470",
   "mosaicBg": "1F3470"
 },
 {
   "name": "Radio Flouka",
   "city": "Paris",
   "country": "France",
   "utc": "·",
   "timezone": "Europe/Paris",
   "slug": "radio-flouka",
   "url": "https://radioflouka.com/",
   "audio": "https://flouka.out.airtime.pro/flouka_a",
   "highlight": "690C1B",
   "fill": "DF888A",
   "sparkle": "690C1B",
   "mosaicBg": "690C1B"
 },
 {
   "name": "Le Mellotron",
   "city": "Paris",
   "country": "France",
   "utc": "·",
   "timezone": "Europe/Paris",
   "slug": "le-mellotron",
   "url": "https://www.lemellotron.com/",
   "audio": "https://play.radioking.io/lemellotron-stream",
   "highlight": "D03D02",
   "fill": "331614",
   "sparkle": "FDBD2B",
   "mosaicBg": "D03D02"
 },
 {
   "name": "*Duuu",
   "city": "Paris",
   "country": "France",
   "utc": "·",
   "timezone": "Europe/Paris",
   "slug": "duuu",
   "url": "https://duuuradio.fr/",
   "audio": "https://duuu.out.airtime.pro/duuu_a",
   "highlight": "",
   "fill": "",
   "sparkle": "",
   "mosaicBg": ""
 },
 {
   "name": "Ola Radio",
   "city": "Bordeaux",
   "country": "France",
   "utc": "·",
   "timezone": "Europe/Paris",
   "slug": "ola-radio",
   "url": "https://olaradio.fr/",
   "audio": "https://ola-radio.radiocult.fm/stream",
   "highlight": "CBCF8B",
   "fill": "FF008A",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Dia Radio",
   "city": "Saint-Jean-de-Luz",
   "country": "France",
   "utc": "·",
   "timezone": "Europe/Paris",
   "slug": "dia-radio",
   "url": "https://www.diaradio.live/",
   "audio": "https://listen.radioking.com/radio/392587/stream/444280",
   "highlight": "24F58C",
   "fill": "3F5C3B",
   "sparkle": "F4F2EA",
   "mosaicBg": "3F5C3B"
 },
 {
   "name": "Radio Raheem",
   "city": "Milan",
   "country": "Italy",
   "utc": "·",
   "timezone": "Europe/Rome",
   "slug": "radio-raheem",
   "url": "http://www.radioraheem.it/",
   "audio": "http://radioraheem.out.airtime.pro:8000/radioraheem_a",
   "highlight": "D8C92B",
   "fill": "3F5C3B",
   "sparkle": "DBCDC2",
   "mosaicBg": ""
 },
 {
   "name": "Rocket Radio 1",
   "city": "Verona",
   "country": "Italy",
   "utc": "·",
   "timezone": "Europe/Rome",
   "slug": "rocket-radio-1",
   "url": "https://rocketradiolive.com/",
   "audio": "https://n05.radiojar.com/nvvyes7gud5tv?rj-ttl=5&rj-tok=AAABhCHWLvoAQ2webGfiqIjQfA",
   "highlight": "3B071E",
   "fill": "8A96B0",
   "sparkle": "1F3470",
   "mosaicBg": "8A96B0"
 },
 {
   "name": "Rocket Radio 2",
   "city": "Verona",
   "country": "Italy",
   "utc": "·",
   "timezone": "Europe/Rome",
   "slug": "rocket-radio-2",
   "url": "https://rocketradiolive.com/",
   "audio": "https://n05.radiojar.com/nvvyes7gud5tv?rj-ttl=5&rj-tok=AAABhCHWLvoAQ2webGfiqIjQfA",
   "highlight": "F75E06",
   "fill": "DF888A",
   "sparkle": "690C1B",
   "mosaicBg": "690C1B"
 },
 {
   "name": "Radio Relativa",
   "city": "Madrid",
   "country": "Spain",
   "utc": "·",
   "timezone": "Europe/Madrid",
   "slug": "radio-relativa",
   "url": "https://radiorelativa.eu/",
   "audio": "https://streamer.radio.co/sd6131729c/listen",
   "highlight": "1F3470",
   "fill": "96B8E3",
   "sparkle": "0000FF",
   "mosaicBg": "96B8E3"
 },
 {
   "name": "Tesla FM",
   "city": "Barcelona",
   "country": "Spain",
   "utc": "·",
   "timezone": "Europe/Madrid",
   "slug": "tesla-fm",
   "url": "https://teslafm.net/",
   "audio": "https://tesla1.teslafm.net:8443/tesla1",
   "highlight": "F75E06",
   "fill": "F4F2EA",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Ness Radio",
   "city": "Marrakesh",
   "country": "Morocco",
   "utc": "·",
   "timezone": "Africa/Casablanca",
   "slug": "ness-radio",
   "url": "http://nessradio.com/",
   "audio": "https://radio.nessradio.net:8212/nessradio",
   "highlight": "331614",
   "fill": "D8C92B",
   "sparkle": "C8A048",
   "mosaicBg": "331614"
 },
 {
   "name": "Radyoon",
   "city": "Tunis",
   "country": "Tunisia",
   "utc": "·",
   "timezone": "Africa/Tunis",
   "slug": "radyoon",
   "url": "https://radyoon.org/",
   "audio": "https://manager7.streamradio.fr:1310/stream?_=1",
   "highlight": "D9EAD3",
   "fill": "F75E06",
   "sparkle": "D9EAD3",
   "mosaicBg": "F75E06"
 },
 {
   "name": "radiOrakel",
   "city": "Oslo",
   "country": "Norway",
   "utc": "·",
   "timezone": "Europe/Oslo",
   "slug": "radi-orakel",
   "url": "https://radiorakel.no/",
   "audio": "https://stream.radiorakel.no/fm993.mp3",
   "highlight": "F4F2EA",
   "fill": "331614",
   "sparkle": "DBCDC2",
   "mosaicBg": "331614"
 },
 {
   "name": "Tīrkultūra ",
   "city": "Riga",
   "country": "Latvia",
   "utc": "·",
   "timezone": "Europe/Riga",
   "slug": "tirkultura",
   "url": "https://www.tirkultura.lv/",
   "audio": "https://s3.radio.co/s216811754/listen",
   "highlight": "F75E06",
   "fill": "CBCF8B",
   "sparkle": "690C1B",
   "mosaicBg": "690C1B"
 },
 {
   "name": "Radio Aparat",
   "city": "Belgrade ",
   "country": "Serbia",
   "utc": "·",
   "timezone": "Europe/Belgrade",
   "slug": "radio-aparat",
   "url": "https://radioaparat.rs/",
   "audio": "https://stream4.rcast.net/72355/",
   "highlight": "D9EAD3",
   "fill": "96B8E3",
   "sparkle": "0000FF",
   "mosaicBg": "0000FF"
 },
 {
   "name": "The Lake Radio",
   "city": "Copenhagen",
   "country": "Denmark",
   "utc": "+2",
   "timezone": "Europe/Copenhagen",
   "slug": "the-lake-radio",
   "url": "https://thelakeradio.com/",
   "audio": "https://thelakeradio.radioca.st/stream",
   "highlight": "F75E06",
   "fill": "331614",
   "sparkle": "DBCDC2",
   "mosaicBg": "331614"
 },
 {
   "name": "Operator Radio",
   "city": "Rotterdam",
   "country": "Netherlands",
   "utc": "·",
   "timezone": "Europe/Amsterdam",
   "slug": "operator-radio",
   "url": "https://www.operator-radio.com/",
   "audio": "https://origin.streamnerd.nl/operator/operator/icecast.audio",
   "highlight": "5A3474",
   "fill": "D9EAD3",
   "sparkle": "C8A048",
   "mosaicBg": "5A3474"
 },
 {
   "name": "Radio Worm",
   "city": "Rotterdam",
   "country": "Netherlands",
   "utc": "·",
   "timezone": "Europe/Amsterdam",
   "slug": "radio-worm",
   "url": "https://radio.worm.org/",
   "audio": "https://play.streamnerd.nl/worm/worm/icecast.audio",
   "highlight": "DBCDC2",
   "fill": "ABA294",
   "sparkle": "DBCDC2",
   "mosaicBg": "331614"
 },
 {
   "name": "Callshop Radio",
   "city": "Düsseldorf",
   "country": "Germany",
   "utc": "·",
   "timezone": "Europe/Berlin",
   "slug": "callshop-radio",
   "url": "https://callshopradio.com/",
   "audio": "https://icecast.callshopradio.com/callshopradio",
   "highlight": "331614",
   "fill": "DBCDC2",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Radio 80000",
   "city": "Munich",
   "country": "Germany",
   "utc": "·",
   "timezone": "Europe/Berlin",
   "slug": "radio-80000",
   "url": "https://www.radio80k.de/",
   "audio": "https://radio80k.out.airtime.pro/radio80k_a",
   "highlight": "D9EAD3",
   "fill": "DF888A",
   "sparkle": "D9EAD3",
   "mosaicBg": "DF888A"
 },
 {
   "name": "Sphere Radio",
   "city": "Leipzig",
   "country": "Germany",
   "utc": "·",
   "timezone": "Europe/Berlin",
   "slug": "sphere-radio",
   "url": "https://sphere-radio.net/",
   "audio": "",
   "highlight": "C55380",
   "fill": "690C1B",
   "sparkle": "DF888A",
   "mosaicBg": "690C1B"
 },
 {
   "name": "Dublab DE",
   "city": "Cologne",
   "country": "Germany",
   "utc": "·",
   "timezone": "Europe/Berlin",
   "slug": "dublab-de",
   "url": "https://dublab.de/",
   "audio": "https://dublabde.out.airtime.pro/dublabde_a",
   "highlight": "3B071E",
   "fill": "DF888A",
   "sparkle": "3B071E",
   "mosaicBg": "3B071E"
 },
 {
   "name": "EOS Radio",
   "city": "Frankfurt am Main",
   "country": "Germany",
   "utc": "·",
   "timezone": "Europe/Berlin",
   "slug": "eos-radio",
   "url": "https://eosradio.de/",
   "audio": "https://s5.radio.co/s21c5fbf27/listen?i1650264069077",
   "highlight": "D9EAD3",
   "fill": "690C1B",
   "sparkle": "DBCDC2",
   "mosaicBg": "690C1B"
 },
 {
   "name": "Cashmere Radio",
   "city": "Wedding",
   "country": "Germany",
   "utc": "·",
   "timezone": "Europe/Berlin",
   "slug": "cashmere-radio",
   "url": "https://cashmereradio.com/",
   "audio": "https://cashmereradio.out.airtime.pro/cashmereradio_a",
   "highlight": "331614",
   "fill": "C8A048",
   "sparkle": "331614",
   "mosaicBg": "C8A048"
 },
 {
   "name": "THF Radio",
   "city": "Berlin",
   "country": "Germany",
   "utc": "·",
   "timezone": "Europe/Berlin",
   "slug": "thf-radio",
   "url": "https://thfradio.de/",
   "audio": "https://thf-radio-7ec0e6ee.radiocult.fm/stream",
   "highlight": "5A3474",
   "fill": "D9EAD3",
   "sparkle": "5A3474",
   "mosaicBg": "5A3474"
 },
 {
   "name": "Refuge Worldwide",
   "city": "Berlin",
   "country": "Germany",
   "utc": "·",
   "timezone": "Europe/Berlin",
   "slug": "refuge-worldwide",
   "url": "https://refugeworldwide.com/",
   "audio": "https://streaming.radio.co/s3699c5e49/listen",
   "highlight": "FDBD2B",
   "fill": "1F3470",
   "sparkle": "FDBD2B",
   "mosaicBg": "1F3470"
 },
 {
   "name": "[sic]nal",
   "city": "Hamburg",
   "country": "Germany",
   "utc": "·",
   "timezone": "Europe/Berlin",
   "slug": "sicnal",
   "url": "https://sicnal.de/",
   "audio": "https://v2202011132974131848.ultrasrv.de:8000/radio.mp3",
   "highlight": "D9EAD3",
   "fill": "5A3474",
   "sparkle": "DBCDC2",
   "mosaicBg": "5A3474"
 },
 {
   "name": "Radio Kapital",
   "city": "Warsaw",
   "country": "Poland",
   "utc": "·",
   "timezone": "Europe/Warsaw",
   "slug": "radio-kapital",
   "url": "https://radiokapital.pl/",
   "audio": "https://radiokapitalpl.out.airtime.pro/radiokapitalpl_a",
   "highlight": "331614",
   "fill": "FF008A",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Punctum Radio",
   "city": "Prague",
   "country": "Czech Republic",
   "utc": "·",
   "timezone": "Europe/Prague",
   "slug": "punctum-radio",
   "url": "https://radiopunctum.cz/",
   "audio": "https://radiopunctum.cz:8001/radio",
   "highlight": "9B5E2F",
   "fill": "DBCDC2",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Radio Rudina",
   "city": "Vienna",
   "country": "Austria",
   "utc": "·",
   "timezone": "Europe/Vienna",
   "slug": "radio-rudina",
   "url": "https://www.radiorudina.com/",
   "audio": "https://azuracast.datea.services:8000/radio.mp3",
   "highlight": "DBCDC2",
   "fill": "331614",
   "sparkle": "DBCDC2",
   "mosaicBg": "331614"
 },
 {
   "name": "Loose Antenna",
   "city": "Lausanne",
   "country": "Switzerland",
   "utc": "·",
   "timezone": "Europe/Zurich",
   "slug": "loose-antenna",
   "url": "https://looseantenna.fm/",
   "audio": "https://stream.looseantenna.fm:8000/default.mp3",
   "highlight": "8A96B0",
   "fill": "1F3470",
   "sparkle": "F4F2EA",
   "mosaicBg": "1F3470"
 },
 {
   "name": "Trnstn Radio",
   "city": "Fribourg",
   "country": "Switzerland",
   "utc": "·",
   "timezone": "Europe/Zurich",
   "slug": "trnstn-radio",
   "url": "http://trnstnradio.com",
   "audio": "",
   "highlight": "3B071E",
   "fill": "24F58C",
   "sparkle": "3B071E",
   "mosaicBg": "3B071E"
 },
 {
   "name": "Radio Bollwerk",
   "city": "Bern",
   "country": "Switzerland",
   "utc": "·",
   "timezone": "Europe/Zurich",
   "slug": "radio-bollwerk",
   "url": "https://www.radio-bollwerk.ch/",
   "audio": "",
   "highlight": "331614",
   "fill": "C55380",
   "sparkle": "F4F2EA",
   "mosaicBg": "C55380"
 },
 {
   "name": "Periszkóp Radio",
   "city": "Budapest",
   "country": "Hungary",
   "utc": "·",
   "timezone": "Europe/Budapest",
   "slug": "periszkop-radio",
   "url": "http://periszkopradio.hu/periweb/?lang=en/",
   "audio": "https://mumia.art.pte.hu:8443/;stream.mp3",
   "highlight": "DBCDC2",
   "fill": "9B5E2F",
   "sparkle": "DBCDC2",
   "mosaicBg": "9B5E2F"
 },
 {
   "name": "Lahmacun",
   "city": "Budapest",
   "country": "Hungary",
   "utc": "·",
   "timezone": "Europe/Budapest",
   "slug": "lahmacun",
   "url": "https://lahmacun.hu/",
   "audio": "https://streaming.lahmacun.hu/radio/8000/radio.mp3",
   "highlight": "D8C92B",
   "fill": "D9EAD3",
   "sparkle": "1F3470",
   "mosaicBg": "1F3470"
 },
 {
   "name": "Retreat Radio",
   "city": "Malmö",
   "country": "Sweden",
   "utc": "·",
   "timezone": "Europe/Stockholm",
   "slug": "retreat-radio",
   "url": "https://www.retreatradio.net/",
   "audio": "https://retreatradio.out.airtime.pro/retreatradio_b",
   "highlight": "331614",
   "fill": "24F58C",
   "sparkle": "3F5C3B",
   "mosaicBg": "331614"
 },
 {
   "name": "103 Инфо ",
   "city": "Skopje",
   "country": "Macedonia",
   "utc": "·",
   "timezone": "Europe/Skopje",
   "slug": "kanal-103",
   "url": "http://www.kanal103.com.mk/",
   "audio": "https://radiostream.neotel.mk/kanal103",
   "highlight": "1F3470",
   "fill": "DBCDC2",
   "sparkle": "1F3470",
   "mosaicBg": "1F3470"
 },
 {
   "name": "20ft Radio",
   "city": "Kiev",
   "country": "Ukraine",
   "utc": "·",
   "timezone": "Europe/Kiev",
   "slug": "20ft-radio",
   "url": "https://www.20ftradio.net/",
   "audio": "https://20ft-radio.radiocult.fm/stream",
   "highlight": "FF008A",
   "fill": "3B071E",
   "sparkle": "F4F2EA",
   "mosaicBg": "3B071E"
 },
 {
   "name": "Grains of Peace",
   "city": "Kiev",
   "country": "Ukraine",
   "utc": "·",
   "timezone": "Europe/Kiev",
   "slug": "grains-for-peace",
   "url": "https://20ftradio.net/grains-of-peace",
   "audio": "https://c34.radioboss.fm/stream/957",
   "highlight": "3B071E",
   "fill": "5A3474",
   "sparkle": "F4F2EA",
   "mosaicBg": "3B071E"
 },
 {
   "name": "Palanga Street Radio",
   "city": "Vilnius ",
   "country": "Lithuania ",
   "utc": "·",
   "timezone": "Europe/Vilnius",
   "slug": "palanga-street-radio",
   "url": "https://palanga.live/",
   "audio": "https://stream.palanga.live/palanga128.mp3",
   "highlight": "D03D02",
   "fill": "C55380",
   "sparkle": "F4F2EA",
   "mosaicBg": "C55380"
 },
 {
   "name": "Radio alHara",
   "city": "Bethlehem",
   "country": "Palestine, State Of",
   "utc": "·",
   "timezone": "Asia/Hebron",
   "slug": "radio-alhara",
   "url": "https://www.radioalhara.net/",
   "audio": "https://n12.radiojar.com/78cxy6wkxtzuv?1650173445=&rj-tok=AAABhCHWLZsAq4KnIDjI52_CAA&rj-ttl=5",
   "highlight": "331614",
   "fill": "FDBD2B",
   "sparkle": "690C1B",
   "mosaicBg": "690C1B"
 },
 {
   "name": "Pan African Space Station",
   "city": "Johannesburg",
   "country": "South Africa",
   "utc": "·",
   "timezone": "Africa/Johannesburg",
   "slug": "pan-african-space-station",
   "url": "https://panafricanspacestation.org.za/",
   "audio": "https://pass.airtime.pro/embed/player?stream=auto",
   "highlight": "ABA294",
   "fill": "9B5E2F",
   "sparkle": "331614",
   "mosaicBg": "9B5E2F"
 },
 {
   "name": "Ida Radio",
   "city": "Helsinki",
   "country": "Finland",
   "utc": "+3",
   "timezone": "Europe/Helsinki",
   "slug": "ida-radio-helsinki",
   "url": "https://idaidaida.net/",
   "audio": "https://broadcast.idaidaida.net:8000/stream",
   "highlight": "690C1B",
   "fill": "DBCDC2",
   "sparkle": "331614",
   "mosaicBg": "690C1B"
 },
 {
   "name": "Ida Radio",
   "city": "Tallinn",
   "country": "Estonia",
   "utc": "+3",
   "timezone": "Europe/Tallinn",
   "slug": "ida-radio",
   "url": "https://idaidaida.net/",
   "audio": "https://broadcast.idaidaida.net:8000/stream",
   "highlight": "690C1B",
   "fill": "DBCDC2",
   "sparkle": "331614",
   "mosaicBg": "690C1B"
 },
 {
   "name": "Stegi Radio (A)",
   "city": "Athens",
   "country": "Greece",
   "utc": "·",
   "timezone": "Europe/Athens",
   "slug": "stegi-radio-a",
   "url": "https://stegi.radio/",
   "audio": "https://movementathens.out.airtime.pro/movementathens_a",
   "highlight": "D9EAD3",
   "fill": "C55380",
   "sparkle": "F4F2EA",
   "mosaicBg": "C55380"
 },
 {
   "name": "Stegi Radio (B)",
   "city": "Athens",
   "country": "Greece",
   "utc": "·",
   "timezone": "Europe/Athens",
   "slug": "stegi-radio-b",
   "url": "https://stegi.radio/",
   "audio": "https://movementathens.out.airtime.pro/movementathens_b",
   "highlight": "F4F2EA",
   "fill": "FDBD2B",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Cannibal Radio",
   "city": "Athens",
   "country": "Greece",
   "utc": "·",
   "timezone": "Europe/Athens",
   "slug": "cannibal-radio",
   "url": "http://cannibalradio.com/",
   "audio": "",
   "highlight": "8A96B0",
   "fill": "DBCDC2",
   "sparkle": "3B071E",
   "mosaicBg": "3B071E"
 },
 {
   "name": "Fade Radio",
   "city": "Athens",
   "country": "Greece",
   "utc": "·",
   "timezone": "Europe/Athens",
   "slug": "fade-radio",
   "url": "https://www.fade.radio/",
   "audio": "https://n02.radiojar.com/072mdmpbfq8uv?1650262434=&rj-tok=AAABhCHWLZ4ACLCFTyyawUpmVg&rj-ttl=5",
   "highlight": "ABA294",
   "fill": "DBCDC2",
   "sparkle": "690C1B",
   "mosaicBg": "690C1B"
 },
 {
   "name": "Paranoise Radio",
   "city": "Thessaloniki",
   "country": "Greece",
   "utc": "·",
   "timezone": "Europe/Athens",
   "slug": "paranoise-radio",
   "url": "https://www.paranoiseradio.com/",
   "audio": "https://paranoisewebcast.radioca.st/stream",
   "highlight": "C8A048",
   "fill": "D9EAD3",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Teder FM",
   "city": "Tel Aviv",
   "country": "Israel",
   "utc": "·",
   "timezone": "Asia/Jerusalem",
   "slug": "teder-fm",
   "url": "https://www.teder.fm/",
   "audio": "https://storage.googleapis.com/teder/2024/12/26.12.24_-_eyal-farchi.mp3",
   "highlight": "331614",
   "fill": "D8C92B",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Radio.Syg.Ma",
   "city": "Moscow",
   "country": "Russia",
   "utc": "·",
   "timezone": "Europe/Moscow",
   "slug": "radio-syg-ma",
   "url": "https://radio.syg.ma/",
   "audio": "https://radio.syg.ma/audio",
   "highlight": "331614",
   "fill": "D9EAD3",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "East East Radio",
   "city": "Doha",
   "country": "Qatar",
   "utc": "+4",
   "timezone": "Asia/Qatar",
   "slug": "east-east-radio",
   "url": "https://easteast.world/en",
   "audio": "https://www.radioking.com/play/easteast-radio",
   "highlight": "331614",
   "fill": "D03D02",
   "sparkle": "F4F2EA",
   "mosaicBg": "D03D02"
 },
 {
   "name": "Mutant Radio",
   "city": "Tbilisi",
   "country": "Georgia",
   "utc": "·",
   "timezone": "Asia/Tbilisi",
   "slug": "mutant-radio",
   "url": "https://mutantradio.net/",
   "audio": "https://listen.radioking.com/radio/282820/stream/328621",
   "highlight": "96B8E3",
   "fill": "D03D02",
   "sparkle": "331614",
   "mosaicBg": "96B8E3"
 },
 {
   "name": "Norrm Radio",
   "city": "Bandung",
   "country": "Indonesia",
   "utc": "·",
   "timezone": "Asia/Jakarta",
   "slug": "norrm-radio",
   "url": "https://www.norrm.com/",
   "audio": "https://listen.norrm.com/default",
   "highlight": "F4F2EA",
   "fill": "C55380",
   "sparkle": "F4F2EA",
   "mosaicBg": "C55380"
 },
 {
   "name": "Paddygrooves Radio",
   "city": "Denpasar",
   "country": "Indonesia",
   "utc": "+7",
   "timezone": "Asia/Makassar",
   "slug": "paddygrooves-radio",
   "url": "https://paddygrooves.radio/",
   "audio": "https://a12.siar.us/radio/8230/radio.mp3",
   "highlight": "FF008A",
   "fill": "3B071E",
   "sparkle": "FF008A",
   "mosaicBg": "FF008A"
 },
 {
   "name": "Hong Kong Community Radio",
   "city": "Hong Kong",
   "country": "Hong Kong",
   "utc": "+8",
   "timezone": "Asia/Hong_Kong",
   "slug": "hong-kong-community-radio",
   "url": "https://www.hkcr.live/",
   "audio": "https://stream.hkcr.live/audio/stream.m3u8",
   "highlight": "24F58C",
   "fill": "D9EAD3",
   "sparkle": "3B071E",
   "mosaicBg": "24F58C"
 },
 {
   "name": "Seoul Community Radio",
   "city": "Seoul",
   "country": "South Korea",
   "utc": "+9",
   "timezone": "Asia/Seoul",
   "slug": "seoul-community-radio",
   "url": "https://seoulcommunityradio.com/",
   "audio": "",
   "highlight": "FDBD2B",
   "fill": "DBCDC2",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Tsubaki FM",
   "city": "Tokyo",
   "country": "Japan",
   "utc": "·",
   "timezone": "Asia/Tokyo",
   "slug": "tsubaki-fm",
   "url": "https://tsubakifm.com",
   "audio": "https://edge.mixlr.com/channel/vgmet",
   "highlight": "C55380",
   "fill": "331614",
   "sparkle": "DBCDC2",
   "mosaicBg": "331614"
 },
 {
   "name": "Data Fruits",
   "city": "Tokyo",
   "country": "Japan",
   "utc": "·",
   "timezone": "Asia/Tokyo",
   "slug": "data-fruits",
   "url": "https://datafruits.fm/",
   "audio": "https://streampusher-relay.club/datafruits.mp3",
   "highlight": "CBCF8B",
   "fill": "24F58C",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Hope St Radio",
   "city": "Melbourne",
   "country": "Australia",
   "utc": "+10",
   "timezone": "Australia/Melbourne",
   "slug": "hope-st-radio",
   "url": "https://www.hopestradio.community/",
   "audio": "https://hope-st-radeio.radiocult.fm/stream",
   "highlight": "331614",
   "fill": "DBCDC2",
   "sparkle": "331614",
   "mosaicBg": "331614"
 },
 {
   "name": "Skylab Radio",
   "city": "Melbourne",
   "country": "Australia",
   "utc": "·",
   "timezone": "Australia/Melbourne",
   "slug": "skylab-radio",
   "url": "https://skylab-radio.com/pages/",
   "audio": "https://stream.skylab-radio.com/live",
   "highlight": "ABA294",
   "fill": "F4F2EA",
   "sparkle": "3B071E",
   "mosaicBg": "3B071E"
 },
 {
   "name": "Area 3000",
   "city": "Melbourne",
   "country": "Australia",
   "utc": "·",
   "timezone": "Australia/Melbourne",
   "slug": "area-3000",
   "url": "https://www.area3000.radio/",
   "audio": "https://area-3000.radiocult.fm/stream",
   "highlight": "8A96B0",
   "fill": "0000FF",
   "sparkle": "F4F2EA",
   "mosaicBg": "0000FF"
 }
//  {
//    "name": "•",
//    "city": "",
//    "country": "",
//    "utc": "·",
//    "timezone": "",
//    "about": "Area 3000 is a digital radio and media platform dedicated to amplifying local voices, fostering community, and showcasing underground music.\n\nBorn during Melbourne’s 2020 lockdowns, when the future of live music and nightclubbing was uncertain, Area 3000 was created to give artists—especially emerging and underrepresented voices—a platform to share their music and stories. We connect our local dance music scene to the wider community through 24/7 broadcasting, storytelling podcasts, live events, and artist development.\n\nOur mission is to bring people together through the power of music by delivering diverse, innovative, and immersive experiences. Our studio is based in Revolver Lane, a creative co-working space in Prahran, Melbourne, on Wurundjeri land.\n\nWe acknowledge the Traditional Owners of the land on which we broadcast and pay our respects to their Elders—past, present, and emerging.",
//    "slug": "",
//    "url": "",
//    "audio": "https://area-3000.radiocult.fm/stream",
//    "highlight": "",
//    "fill": "",
//    "sparkle": ""
//  }
];